### PR TITLE
Update documentation for metal-cli/liferay-npm-bundler

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
@jbalsas could you please have a look at this when you get a chance. Thanks!

**Comment by jbalsas** [comment]
Yeah, I'll merge this right away. Now that we're almost done with `npm-scripts`... @bryceosterhaus, could you please update this? Right now is being published at https://ui-migration.liferay.com/docs/javascript/metal-cli.html

Thanks!

**Comment by bryceosterhaus** [comment]
Update docs to reflect using npm-scripts?

**Comment by jbalsas** [comment]
Yes please! That way we can direct anyone wondering how to setup a module with JS to that documentation.

**Pull request merged**
